name: Go
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set Up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
      - name: Lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          fail_on_error: true